const GET_JOBS: string = "GET_JOBS";
const GET_JOBS_SEARCH_RESULTS : string = "GET_JOBS_SEARCH_RESULTS";
const CLEAR_JOBS_SEARCH_RESULTS : string = "CLEAR_JOBS_SEARCH_RESULTS";
const SET_SEARCH_LOADER : string = "SET_SEARCH_LOADER";
const GET_SINGLE_JOB : string = "GET_SINGLE_JOB";
const GET_RELATED_JOBS : string = "GET_RELATED_JOBS";
const GET_RELATED_SKILLS: string = "GET_RELATED_SKILLS";
const GET_SINGLE_SKILL : string = "GET_SINGLE_SKILL";
const GET_SKILL_RELATED_SKILLS : string = "GET_SKILL_RELATED_SKILLS";
const GET_SKILL_RELATED_JOBS : string = "GET_SKILL_RELATED_JOBS";

const Types = {
    GET_JOBS,
    GET_JOBS_SEARCH_RESULTS,
    CLEAR_JOBS_SEARCH_RESULTS,
    SET_SEARCH_LOADER,
    GET_SINGLE_JOB,
    GET_RELATED_JOBS,
    GET_RELATED_SKILLS,
    GET_SINGLE_SKILL,
    GET_SKILL_RELATED_SKILLS,
    GET_SKILL_RELATED_JOBS
}

export default Types;